### ISSUE TITLE
Completion broken

### ISSUE THREAD

**Issue by tpope** [tpope/vim-heroku#6]
`heroku commands --json` has disappeared without warning and I have no idea which of the 200 node modules is even responsible.

**Comment by jdxcode** [comment]
hey @tpope, apologies about this. `heroku commands` was supposed to be some internal functionality we don't need anymore. It might be useful in some meta-contexts like this though. I'll look into adding it back. It won't be 100% the same as it was before, but I'll test it with this plugin to make sure it still works or at least make a PR here so it'll work.

**Comment by tpope** [comment]
Thanks.

FYI this actually affects more than just completion, as I also use the results to determine whether it is safe to inject the current app with `-a` into the command line.

**Comment by jdxcode** [comment]
I put a [partial patch](https://github.com/tpope/vim-heroku/pull/7) in for the command names at least. You'll need to update to the beta for it to work until it's released `heroku update beta`. I might need a bit of help to fix it further though. My vimscript skill isn't that great and I'm having trouble getting the flags to work.

Some of the changes in v7 that are worth noting:
* flags is a map instead of an array now
* wantsApp/needsApp were removed. I we could use the existence of a `--app` flag to estimate if it takes an app flag though. There are a couple of cases where `--app` wouldn't be an app you can look up, but I don't think it's important for this purpose.
* hasValue was removed. In the code, we now have flag "types" like `boolean` and `string`. I could actually add this back in if we need it but my first glance at the code in this plugin didn't look like it was necessary.

**Comment by tpope** [comment]
```
% heroku update beta                                                      
heroku: Updating CLI... not updatable
Updating completions... done
```
Running on Ubuntu. Is this something that make take a bit to roll out?

**Comment by tpope** [comment]
While waiting on that, can you show me some example JSON of a command - something with a few different kinds of flags - so I can assess next steps? You are almost certainly correct that the removal of `wantsApp`/`needsApp`/`hasValue` won't be a problem.

**Comment by jdxcode** [comment]
@tpope just pushed 7.0.61 with this change in, but here is the [full json](https://gist.github.com/jdxcode/1ea8757545a7f08eb58a25f841bf9298)

**Comment by tpope** [comment]
Took your patch and ran with it, I think we're good. Thanks!

**Comment by jdxcode** [comment]
sorry for the trouble!

**Comment by tpope** [comment]
Is there an issue tracker or anything for future things of this nature? Main point of frustration was not having any actionable steps I could take.

**Comment by jdxcode** [comment]
`heroku commands --json` was not supposed to be used by anyone except us so we didn't communicate that it was going away. We will post any possible breakages with the CLI behavior in the Heroku Changelog, but it's extremely rare we ever make any breaking changes with things we know people are actively using.
